### ISSUE TITLE
Can't convert image

### ISSUE THREAD

**Issue by urgonguyen** [RomRoc/deeplab_retrain_ade20k_colab#3]
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-05-24 21:06:31.776841: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-05-24 21:06:31.777351: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:04.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2018-05-24 21:06:31.777394: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-05-24 21:06:32.147098: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-05-24 21:06:32.147158: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-05-24 21:06:32.147184: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-05-24 21:06:32.147553: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10765 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7)
2018-05-24 21:06:32.389570: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-05-24 21:06:32.389660: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-05-24 21:06:32.389692: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-05-24 21:06:32.389718: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-05-24 21:06:32.389885: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10765 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7)
>> Converting image 1/2094 shard 0Traceback (most recent call last):
  File "./build_food17_data.py", line 116, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "./build_food17_data.py", line 111, in main
    'train', FLAGS.train_image_folder, FLAGS.train_image_label_folder)
  File "./build_food17_data.py", line 96, in _convert_dataset
    seg_data = tf.gfile.FastGFile(seg_filename, 'r').read()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 120, in read
    self._preread_check()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 80, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: ./food_seg/FOOD/annotations/training/168855.png; No such file or directory
what happen?help me,please
when I run : 
%cd ~/drive/app/food/models/research/deeplab/datasets/food_seg/FOOD/anotations/training/
=> /content/drive/app/food/models/research/deeplab/datasets/food_seg/FOOD/anotations/training

**Comment by RomRoc** [comment]
This repository is only about ADE20K dataset, not using own dataset.
I'm working for custom dataset Google Colab train in Deeplab.
